<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>XProj.Plugin.Translator</RootNamespace>
        <AssemblyName>XProj.Plugin.Translator</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\XProj.Plugin.Abstractions\XProj.Plugin.Abstractions.csproj" />
        <PackageReference Include="Material.Icons.WPF" Version="3.0.2" />
    </ItemGroup>

</Project>
